# Setup
title:        Cayman theme
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
url:          https://github.com/jasonlong/cayman-theme

# About/contact
author:
  name:       Jason Long
  url:        http://github.com/jasonlong
  email:      youremail@domain.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: redcarpet