# Setup
title:        冉天华的博客
tagline:      用文字记录我的成长！
baseurl:      ""
paginate:     5
locale:       "zh"

# About/contact
author:
  name:       冉天华（Jerome）
  url:        https://github.com/rantianhua

# Gems
gems:
  - jekyll-paginate

plugins: [jekyll-paginate]

#Others
markdown: kramdown